language: r

r_packages:
- dplyr
- ncdf4

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: lskIDwNSMSJ9zcB7x7EgeNBarfE4VWl7fLi/XvmX0fRYJCV/0rTT9bF0iPtCGJVJ5rLQgB3dskb2o2s11mLxKPKsLTRRejN1IUY81X3/ZwHjKykFn1JIJ7C9os/4Q2uR9j/RcMIa+f9pmgyhdQVySvc/p0ACcAaUcDmNHdihnzY=
